version: 2
updates:
    - package-ecosystem: github-actions
      directory: /
      schedule:
          interval: weekly
      groups:
          github-actions:
              patterns:
                  - '*'

    - package-ecosystem: npm
      directory: /
      schedule:
          interval: weekly
      groups:
          npm-patch:
              patterns:
                  - '*'
              update-types:
                  - patch
          npm-minor:
              patterns:
                  - '*'
              update-types:
                  - minor
          npm-major:
              patterns:
                  - '*'
              update-types:
                  - major
