version: 2
updates:
    - package-ecosystem: github-actions
      directory: /
      schedule:
          interval: weekly
      groups:
          github-actions:
              patterns:
                  - '*'
      cooldown:
          default-days: 10

    - package-ecosystem: npm
      directory: /
      schedule:
          interval: weekly
      groups:
          npm-patch:
              patterns:
                  - '*'
              update-types:
                  - patch
          npm-minor:
              patterns:
                  - '*'
              update-types:
                  - minor
          npm-major:
              patterns:
                  - '*'
              update-types:
                  - major
      cooldown:
          default-days: 10
          semver-patch-days: 5
          semver-minor-days: 10
          semver-major-days: 20
